apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: clan-api
  name: clan-api
  namespace: default
spec:
  serviceName: "clan-api"
  replicas: 1
  selector:
    matchLabels:
      service: clan-api
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: clan-api
    spec:
      containers:
        - image: maksim1111/clan-api:latest
          name: clan-api
          imagePullPolicy: IfNotPresent
          command: [ "/app/main" ]
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - mountPath: /app/storage
              subPath: storage
              name: clan-api-data
          env:
            - name: DB_PATH
              value: /app/storage/db.sqlite
          envFrom:
            - secretRef:
                name: clan-api-secrets
          readinessProbe:
            exec:
              command: ["sqlite3", "/app/storage/db.sqlite", ".tables"]
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
  volumeClaimTemplates:
    - metadata:
        name: clan-api-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "do-block-storage"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: clan-api
  name: clan-api
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    service: clan-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clan-api
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: clan-api.mxksim.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clan-api
                port:
                  number: 8080
